name: Sync docs to Wiki

on:
  push:
    branches:
      - main
      - feat-agents-skill-and-add-trigger-in-sync-wiki-action
    paths:
      - '.docs/**'
  workflow_dispatch:

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync docs to wiki
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./.github/wf_scripts/sync-docs-to-wiki.sh
          ./.github/wf_scripts/sync-docs-to-wiki.sh
